# Generated by Django 3.2.6 on 2021-10-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
